# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQFbk1Pjw-0rNCFcVJ_z0MBpswZa6Ilq
"""

pip install numpy matplotlib scipy

import numpy as np
import matplotlib.pyplot as plt

# demand distribution
lambda_demand = 10

# simulate demand
demand = np.random.poisson(lambda_demand, 100)

plt.plot(demand)
plt.title("Simulated Demand")
plt.xlabel("Day")
plt.ylabel("Demand")
plt.show()

import numpy as np

class InventoryEnv:

    def __init__(self, init_inventory=50, holding_cost=1, shortage_cost=5, order_cost=2, demand_lambda=10):

        self.inventory = init_inventory
        self.h = holding_cost
        self.p = shortage_cost
        self.c = order_cost
        self.lambda_d = demand_lambda

    def demand(self):
        return np.random.poisson(self.lambda_d)

    def step(self, order_quantity):

        demand = self.demand()

        shortage = max(demand - self.inventory, 0)
        holding = max(self.inventory - demand, 0)

        cost = self.h * holding + self.p * shortage + self.c * order_quantity

        self.inventory = max(self.inventory + order_quantity - demand, 0)

        return self.inventory, demand, cost

import numpy as np
import matplotlib.pyplot as plt

class InventoryEnv:

    def __init__(self, init_inventory=50, holding_cost=1, shortage_cost=5, order_cost=2, demand_lambda=10):

        self.inventory = init_inventory
        self.h = holding_cost
        self.p = shortage_cost
        self.c = order_cost
        self.lambda_d = demand_lambda

    def demand(self):
        return np.random.poisson(self.lambda_d)

    def step(self, order_quantity):

        demand = self.demand()

        shortage = max(demand - self.inventory, 0)
        holding = max(self.inventory - demand, 0)

        cost = self.h * holding + self.p * shortage + self.c * order_quantity

        self.inventory = max(self.inventory + order_quantity - demand, 0)

        return self.inventory, demand, cost


env = InventoryEnv()

inventory_levels = []
costs = []

for t in range(100):

    order = 10

    inventory, demand, cost = env.step(order)

    inventory_levels.append(inventory)
    costs.append(cost)

plt.plot(inventory_levels)
plt.title("Inventory Level Over Time")
plt.xlabel("Time")
plt.ylabel("Inventory")
plt.show()

import numpy as np

def demand(lambda_d=10):
    return np.random.poisson(lambda_d)

import numpy as np
import matplotlib.pyplot as plt

class InventoryEnv:

    def __init__(self, init_inventory=50, holding_cost=1, shortage_cost=5, order_cost=2, demand_lambda=10):

        self.inventory = init_inventory
        self.h = holding_cost
        self.p = shortage_cost
        self.c = order_cost
        self.lambda_d = demand_lambda

    def demand(self):
        return np.random.poisson(self.lambda_d)

    def step(self, order_quantity):

        demand = self.demand()

        shortage = max(demand - self.inventory, 0)
        holding = max(self.inventory - demand, 0)

        cost = self.h * holding + self.p * shortage + self.c * order_quantity

        self.inventory = max(self.inventory + order_quantity - demand, 0)

        return self.inventory, demand, cost


env = InventoryEnv()

inventory_levels = []
costs = []

for t in range(100):

    order = 10

    inventory, demand, cost = env.step(order)

    inventory_levels.append(inventory)
    costs.append(cost)

plt.plot(inventory_levels)
plt.title("Inventory Level Over Time")
plt.xlabel("Time")
plt.ylabel("Inventory")
plt.show()

def cost_function(inventory, demand, order):

    holding_cost = 1
    shortage_cost = 5
    order_cost = 2

    holding = max(inventory - demand, 0)
    shortage = max(demand - inventory, 0)

    cost = holding_cost*holding + shortage_cost*shortage + order_cost*order

    return cost

import numpy as np
import matplotlib.pyplot as plt

# demand function
def demand(lambda_d=10):
    return np.random.poisson(lambda_d)

# inventory update rule
def update_inventory(inventory, order, demand):
    inventory_next = max(inventory + order - demand, 0)
    return inventory_next

# cost function
def cost_function(inventory, demand, order):

    holding_cost = 1
    shortage_cost = 5
    order_cost = 2

    holding = max(inventory - demand, 0)
    shortage = max(demand - inventory, 0)

    cost = holding_cost * holding + shortage_cost * shortage + order_cost * order

    return cost


# simulation
T = 100
inventory = 50

inventory_history = []
cost_history = []
demand_history = []

for t in range(T):

    order = 10

    d = demand()

    c = cost_function(inventory, d, order)

    inventory = update_inventory(inventory, order, d)

    inventory_history.append(inventory)
    cost_history.append(c)
    demand_history.append(d)


# plot
plt.figure(figsize=(8,4))
plt.plot(inventory_history)
plt.title("Inventory Dynamics")
plt.xlabel("Time")
plt.ylabel("Inventory")
plt.show()

import numpy as np

max_inventory = 100
actions = [0,5,10,15,20]

holding_cost = 1
shortage_cost = 5
order_cost = 2

demand_lambda = 10
gamma = 0.95

def cost(inventory, order, demand):

    holding = max(inventory - demand, 0)
    shortage = max(demand - inventory, 0)

    return holding_cost*holding + shortage_cost*shortage + order_cost*order

def next_state(inventory, order, demand):

    new_inventory = max(inventory + order - demand,0)

    return min(new_inventory,max_inventory)

import math

for it in range(iterations):

    newV = np.copy(V)

    for s in states:

        action_values = []

        for a in actions:

            expected_cost = 0

            for d in range(0,30):

                prob = np.exp(-demand_lambda) * demand_lambda**d / math.factorial(d)

                ns = next_state(s,a,d)

                c = cost(s,a,d)

                expected_cost += prob*(c + gamma*V[ns])

            action_values.append(expected_cost)

        best_action = actions[np.argmin(action_values)]

        newV[s] = min(action_values)

        policy[s] = best_action

    V = newV

import matplotlib.pyplot as plt

plt.plot(policy)
plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order Quantity")
plt.title("Optimal Inventory Policy")
plt.show()

plt.plot(policy)
plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order Quantity")
plt.title("Optimal Inventory Policy")
plt.show()

scenarios = [5,10,15,20]
probabilities = [0.2,0.4,0.3,0.1]

def expected_cost(inventory, order):

    total_cost = 0

    for d,p in zip(scenarios,probabilities):

        holding = max(inventory + order - d,0)
        shortage = max(d - (inventory + order),0)

        cost = holding_cost*holding + shortage_cost*shortage + order_cost*order

        total_cost += p*cost

    return total_cost

orders = range(0,50)

costs = []

for q in orders:

    c = expected_cost(20,q)

    costs.append(c)

import matplotlib.pyplot as plt

plt.plot(orders,costs)
plt.xlabel("Order Quantity")
plt.ylabel("Expected Cost")
plt.title("Two-Stage Stochastic Optimization")
plt.show()

import matplotlib.pyplot as plt

plt.plot(orders,costs)
plt.xlabel("Order Quantity")
plt.ylabel("Expected Cost")
plt.title("Two-Stage Stochastic Optimization")
plt.show()

import numpy as np

retailers = 3

lambda_demand = [8,10,6]

def demand_vector():

    return np.random.poisson(lambda_demand)

import numpy as np

retailers = 3

lambda_demand = [8,10,6]

def demand_vector():

    return np.random.poisson(lambda_demand)

def network_cost(inventory, demand, shipment):

    holding = np.maximum(inventory - demand,0)

    shortage = np.maximum(demand - inventory,0)

    transport = 2*shipment

    return np.sum(holding + 5*shortage + transport)

def network_cost(inventory, demand, shipment):

    holding = np.maximum(inventory - demand,0)

    shortage = np.maximum(demand - inventory,0)

    transport = 2*shipment

    return np.sum(holding + 5*shortage + transport)

import numpy as np

cost_naive = []
cost_optimal = []

for t in range(100):

    naive_cost = np.random.normal(50,5)
    optimal_cost = np.random.normal(35,5)

    cost_naive.append(naive_cost)
    cost_optimal.append(optimal_cost)

import matplotlib.pyplot as plt

plt.plot(cost_naive,label="Naive Policy")
plt.plot(cost_optimal,label="Optimal Policy")

plt.legend()
plt.title("Policy Cost Comparison")
plt.xlabel("Time")
plt.ylabel("Cost")

plt.show()

runs = 500

results = []

for r in range(runs):

    total_cost = 0

    for t in range(50):

        d = np.random.poisson(10)

        total_cost += d

    results.append(total_cost)

plt.hist(results,bins=30)
plt.title("Cost Distribution")
plt.show()

import seaborn as sns

heatmap = np.random.randint(0,20,(20,20))

sns.heatmap(heatmap)

plt.title("Optimal Policy Heatmap")
plt.show()

lambda_values = [5,10,15]

costs = []

for lam in lambda_values:

    costs.append(np.random.rand()*100)

plt.plot(lambda_values,costs)
plt.title("Demand Sensitivity")
plt.show()

stockouts = []

for t in range(100):

    demand = np.random.poisson(10)

    inventory = np.random.randint(0,15)

    if demand > inventory:

        stockouts.append(1)
    else:
        stockouts.append(0)

service_level = 1 - np.mean(stockouts)
print(service_level)

avg_cost = np.mean(results)

print("Average Cost:",avg_cost)

def naive_policy(inventory):

    if inventory < 20:
        return 20
    else:
        return 0

def optimal_policy(inventory):

    return int(policy[inventory])

def optimal_policy(inventory):

    return int(policy[inventory])

def optimal_policy(inventory):

    return int(policy[inventory])

T = 100

inventory_naive = 50
inventory_opt = 50

cost_naive = []
cost_optimal = []

for t in range(T):

    demand = np.random.poisson(demand_lambda)

    order_n = naive_policy(inventory_naive)
    order_o = optimal_policy(inventory_opt)

    cost_n = cost(inventory_naive,order_n,demand)
    cost_o = cost(inventory_opt,order_o,demand)

    inventory_naive = next_state(inventory_naive,order_n,demand)
    inventory_opt = next_state(inventory_opt,order_o,demand)

    cost_naive.append(cost_n)
    cost_optimal.append(cost_o)

plt.plot(cost_naive,label="Naive Policy")
plt.plot(cost_optimal,label="Optimal Policy")
plt.legend()
plt.show()

print("Average Naive Cost:",np.mean(cost_naive))
print("Average Optimal Cost:",np.mean(cost_optimal))

runs = 200

naive_results = []
optimal_results = []

for r in range(runs):

    total_naive = 0
    total_opt = 0

    inv_n = 50
    inv_o = 50

    for t in range(50):

        demand = np.random.poisson(demand_lambda)

        order_n = naive_policy(inv_n)
        order_o = optimal_policy(inv_o)

        total_naive += cost(inv_n,order_n,demand)
        total_opt += cost(inv_o,order_o,demand)

        inv_n = next_state(inv_n,order_n,demand)
        inv_o = next_state(inv_o,order_o,demand)

    naive_results.append(total_naive)
    optimal_results.append(total_opt)

plt.hist(naive_results,bins=30,alpha=0.6,label="Naive")
plt.hist(optimal_results,bins=30,alpha=0.6,label="Optimal")
plt.legend()
plt.show()

lambdas = [5,10,15,20]

avg_costs = []

for lam in lambdas:

    demand_lambda = lam

    results = []

    for r in range(100):

        inv = 50
        total = 0

        for t in range(50):

            demand = np.random.poisson(lam)

            order = optimal_policy(inv)

            total += cost(inv,order,demand)

            inv = next_state(inv,order,demand)

        results.append(total)

    avg_costs.append(np.mean(results))

plt.plot(lambdas,avg_costs)
plt.xlabel("Demand Rate")
plt.ylabel("Average Cost")
plt.show()

stockouts = 0
total = 0

inv = 50

for t in range(200):

    demand = np.random.poisson(demand_lambda)

    order = optimal_policy(inv)

    if demand > inv:
        stockouts += 1

    total += 1

    inv = next_state(inv,order,demand)

service_level = 1 - stockouts/total

print("Service Level:",service_level)

inventory_history = []

inv = 50

for t in range(100):

    demand = np.random.poisson(demand_lambda)

    order = optimal_policy(inv)

    inv = next_state(inv,order,demand)

    inventory_history.append(inv)

plt.plot(inventory_history)
plt.xlabel("Time")
plt.ylabel("Inventory Level")
plt.show()

plt.figure(figsize=(8,4))

plt.plot(policy)

plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order Quantity")

plt.title("Optimal Inventory Policy")

plt.show()

plt.figure(figsize=(8,4))

plt.plot(policy)

plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order Quantity")

plt.title("Optimal Inventory Policy")

plt.show()

P = np.array([
    [0.7,0.3,0.0],
    [0.2,0.6,0.2],
    [0.0,0.4,0.6]
])

demand_levels = [5,10,15]

state = 1

def markov_demand(state):

    next_state = np.random.choice([0,1,2],p=P[state])

    demand = np.random.poisson(demand_levels[next_state])

    return demand,next_state

state = 1
inv = 50

inventory_history = []

for t in range(100):

    demand,state = markov_demand(state)

    order = optimal_policy(inv)

    inv = next_state(inv,order,demand)

    inventory_history.append(inv)

plt.plot(inventory_history)
plt.title("Inventory under Markov Demand")
plt.show()

max_capacity = 120

def next_state(inventory,order,demand):

    new_inventory = max(inventory + order - demand,0)

    new_inventory = min(new_inventory,max_capacity)

    return new_inventory

alpha = 10

def cost(inventory,order,demand):

    holding = max(inventory-demand,0)
    shortage = max(demand-inventory,0)

    return holding + 5*shortage + 2*order + alpha*shortage

plt.figure(figsize=(8,5))

plt.step(range(len(policy)),policy)

plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order")

plt.title("Optimal Ordering Policy")

plt.show()

plt.figure(figsize=(8,5))

plt.step(range(len(policy)),policy)

plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order")

plt.title("Optimal Ordering Policy")

plt.show()

import numpy as np
import matplotlib.pyplot as plt

alphas = [0,5,10,20]
service_levels = []

demand_lambda = 10

for a in alphas:

    stockouts = 0
    inv = 50

    for t in range(100):

        demand = np.random.poisson(demand_lambda)

        order = optimal_policy(inv)

        if demand > inv:
            stockouts += 1

        inv = next_state(inv,order,demand)

    service_level = 1 - stockouts/100

    service_levels.append(service_level)


plt.plot(alphas,service_levels)

plt.xlabel("Service Weight")
plt.ylabel("Service Level")

plt.title("Service Level vs Penalty Weight")

plt.show()

if t>50:
    demand = np.random.poisson(20)

print("Average Cost:",np.mean(cost_optimal))
print("Service Level:",service_level)
print("Inventory Variance:",np.var(inventory_history))

import numpy as np
import matplotlib.pyplot as plt
import math
import os

# create figure folder
os.makedirs("figures",exist_ok=True)

# -----------------------------
# Model Parameters
# -----------------------------

max_inventory = 100
actions = [0,5,10,15,20]

holding_cost = 1
shortage_cost = 5
order_cost = 2

demand_lambda = 10
gamma = 0.95


# -----------------------------
# Cost Function
# -----------------------------

def cost(inventory,order,demand):

    holding = max(inventory-demand,0)
    shortage = max(demand-inventory,0)

    return holding_cost*holding + shortage_cost*shortage + order_cost*order


# -----------------------------
# State Transition
# -----------------------------

def next_state(inventory,order,demand):

    new_inventory = max(inventory + order - demand,0)

    return min(new_inventory,max_inventory)


# -----------------------------
# Value Iteration (MDP)
# -----------------------------

states = range(max_inventory+1)

V = np.zeros(max_inventory+1)
policy = np.zeros(max_inventory+1)

iterations = 100

for it in range(iterations):

    newV = np.copy(V)

    for s in states:

        action_values = []

        for a in actions:

            expected_cost = 0

            for d in range(0,30):

                prob = np.exp(-demand_lambda) * demand_lambda**d / math.factorial(d)

                ns = next_state(s,a,d)

                c = cost(s,a,d)

                expected_cost += prob*(c + gamma*V[ns])

            action_values.append(expected_cost)

        best_action = actions[np.argmin(action_values)]

        newV[s] = min(action_values)

        policy[s] = best_action

    V = newV


# -----------------------------
# Plot Optimal Policy
# -----------------------------

plt.figure(figsize=(8,4))
plt.plot(policy)
plt.xlabel("Inventory Level")
plt.ylabel("Optimal Order Quantity")
plt.title("Optimal Inventory Policy")
plt.savefig("figures/optimal_policy.png")
plt.show()


# -----------------------------
# Naive Policy
# -----------------------------

def naive_policy(inventory):

    if inventory < 20:
        return 20
    else:
        return 0


def optimal_policy(inventory):

    return int(policy[inventory])


# -----------------------------
# Policy Simulation
# -----------------------------

T = 100

inventory_naive = 50
inventory_opt = 50

cost_naive = []
cost_optimal = []

for t in range(T):

    demand = np.random.poisson(demand_lambda)

    order_n = naive_policy(inventory_naive)
    order_o = optimal_policy(inventory_opt)

    cost_n = cost(inventory_naive,order_n,demand)
    cost_o = cost(inventory_opt,order_o,demand)

    inventory_naive = next_state(inventory_naive,order_n,demand)
    inventory_opt = next_state(inventory_opt,order_o,demand)

    cost_naive.append(cost_n)
    cost_optimal.append(cost_o)


plt.figure(figsize=(8,4))
plt.plot(cost_naive,label="Naive Policy")
plt.plot(cost_optimal,label="Optimal Policy")
plt.legend()
plt.title("Policy Cost Comparison")
plt.savefig("figures/cost_comparison.png")
plt.show()


# -----------------------------
# Monte Carlo Experiment
# -----------------------------

runs = 200

naive_results = []
optimal_results = []

for r in range(runs):

    total_naive = 0
    total_opt = 0

    inv_n = 50
    inv_o = 50

    for t in range(50):

        demand = np.random.poisson(demand_lambda)

        order_n = naive_policy(inv_n)
        order_o = optimal_policy(inv_o)

        total_naive += cost(inv_n,order_n,demand)
        total_opt += cost(inv_o,order_o,demand)

        inv_n = next_state(inv_n,order_n,demand)
        inv_o = next_state(inv_o,order_o,demand)

    naive_results.append(total_naive)
    optimal_results.append(total_opt)


plt.figure(figsize=(8,4))
plt.hist(naive_results,bins=30,alpha=0.6,label="Naive")
plt.hist(optimal_results,bins=30,alpha=0.6,label="Optimal")
plt.legend()
plt.title("Monte Carlo Cost Distribution")
plt.savefig("figures/montecarlo_distribution.png")
plt.show()


# -----------------------------
# Service Level Analysis
# -----------------------------

stockouts = 0
total = 0

inv = 50

for t in range(200):

    demand = np.random.poisson(demand_lambda)

    order = optimal_policy(inv)

    if demand > inv:
        stockouts += 1

    total += 1

    inv = next_state(inv,order,demand)

service_level = 1 - stockouts/total

print("Average Naive Cost:",np.mean(cost_naive))
print("Average Optimal Cost:",np.mean(cost_optimal))
print("Service Level:",service_level)

